version: '3'
services:
  be-api:
    image: kienvipmkvn/be
    mem_limit: 512m
    environment:
      - MYSQL_SERVER=172.31.17.46
      - MYSQL_PORT=3306
      - MYSQL_INITIAL_CATALOG=datn
      - MYSQL_USERNAME=dtkien
      - MYSQL_PASSWORD=123456789@Abc
  front-nginx:
    image: kienvipmkvn/front-nginx
    environment:
      - NODE_ENV=production
    mem_limit: 512m
    ports:
      - 80:80