version: '3'
services:

  front-admin:
    image: kienvipmkvn/front-admin
    mem_limit: 512m
    hostname: front-admin
    ports:
      - 80:80
  be:
    image: kienvipmkvn/be
    mem_limit: 512m
    hostname: be
    environment:
      - MYSQL_SERVER='host.docker.internal'
      - MYSQL_PORT='3306'
      - MYSQL_INITIAL_CATALOG='datn'
      - MYSQL_USERNAME='root'
      - MYSQL_PASSWORD='123456'
    ports:
      - 7218:7218