version: '3'
services:
  be-api:
    build:
      dockerfile: Dockerfile.dev
      context: ./DATN-GracefulStyleShop-BE
    environment:
      - MYSQL_SERVER=host.docker.internal
      - MYSQL_PORT=3306
      - MYSQL_INITIAL_CATALOG=datn
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=123456

  front-admin:
    build:
      dockerfile: Dockerfile.dev
      context: ./DATN-GracefulStyleShop-ADMIN
      args:
        - VUE_APP_BASE_API_URL=/api/v1
    volumes:
      - /home/node/app/admin/node_modules
      - ./DATN-GracefulStyleShop-ADMIN:/home/node/app/admin
    ports:
      - 3000:8080

  front-client:
    build:
      dockerfile: Dockerfile.dev
      context: ./DATN-GracefulStyleShop-FE
      args:
        - VUE_APP_BASE_API_URL=/api/v1
    volumes:
      - /home/node/app/node_modules
      - ./DATN-GracefulStyleShop-FE:/home/node/app
    ports:
      - 5000:8080

  front-nginx:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - 80:80
    depends_on:
      - front-admin
      - front-client
      - be-api