version: '3'
services:
  be-api:
    image: kienvipmkvn/be
    mem_limit: 512m
    environment:
      - MYSQL_SERVER=14.225.255.150
      - MYSQL_PORT=3306
      - MYSQL_INITIAL_CATALOG=datn
      - MYSQL_USERNAME=dtkien
      - MYSQL_PASSWORD=123456
  front-nginx:
    image: kienvipmkvn/front-nginx
    mem_limit: 512m
    ports:
      - 80:80