version: '3'
services:

  front-admin:
    image: kienvipmkvn/front-admin
    mem_limit: 512m
    hostname: front-admin
  be:
    image: kienvipmkvn/be
    mem_limit: 512m
    hostname: be
    environment:
      - MYSQL_SERVER='host.docker.internal'
      - MYSQL_PORT='3306'
      - MYSQL_INITIAL_CATALOG='datn'
      - MYSQL_USERNAME='root'
      - MYSQL_PASSWORD='123456'
  nginx:
    image: 'kienvipmkvn/multi-nginx'
    mem_limit: 512m
    hostname: nginx
    ports:
      - '80:80'