version: '3'
services:
  be-api:
    build: ./DATN-GracefulStyleShop-BE
    environment:
      - MYSQL_SERVER=14.225.255.150
      - MYSQL_PORT=3306
      - MYSQL_INITIAL_CATALOG=datn
      - MYSQL_USERNAME=dtkien
      - MYSQL_PASSWORD=123456
  front-nginx:
    build:
      context: .
      args:
        VUE_APP_BASE_API_URL: /api/v1
    ports:
      - '80:80'