# build stage
FROM node:lts-alpine
ARG VUE_APP_BASE_API_URL
ENV VUE_APP_BASE_API_URL ${VUE_APP_BASE_API_URL}
USER node
RUN mkdir -p /home/node/app/admin
WORKDIR /home/node/app/admin
 
COPY --chown=node:node ./package.json ./

RUN npm install
COPY --chown=node:node ./ ./
CMD ["npm", "run", "serve"]