//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATN.DTKIEN.GracefulStyleShop.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DATN.DTKIEN.GracefulStyleShop.Common.Resources.ResourceVI", typeof(ResourceVI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  không hợp lệ..
        /// </summary>
        public static string DateInvalid {
            get {
                return ResourceManager.GetString("DateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string DateOfBirthName {
            get {
                return ResourceManager.GetString("DateOfBirthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban đã tồn tại..
        /// </summary>
        public static string DepartmentCodeAlreadyExist {
            get {
                return ResourceManager.GetString("DepartmentCodeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban mã &lt;{0}&gt; không tồn tại..
        /// </summary>
        public static string DepartmentCodeNotAlreadyExist {
            get {
                return ResourceManager.GetString("DepartmentCodeNotAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phòng ban đã tồn tại..
        /// </summary>
        public static string DepartmentNameAlreadyExist {
            get {
                return ResourceManager.GetString("DepartmentNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban không tồn tại..
        /// </summary>
        public static string DepartmentNotAlreadyExist {
            get {
                return ResourceManager.GetString("DepartmentNotAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại..
        /// </summary>
        public static string EmpCodeAlreadyExist {
            get {
                return ResourceManager.GetString("EmpCodeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên &lt;{0}&gt; đã tồn tại..
        /// </summary>
        public static string EmpCodeNameAlreadyExist {
            get {
                return ResourceManager.GetString("EmpCodeNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên trùng với nhân viên dòng {0}..
        /// </summary>
        public static string ErrorRowDaplicateImport {
            get {
                return ResourceManager.GetString("ErrorRowDaplicateImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng thử lại..
        /// </summary>
        public static string ErrorServer {
            get {
                return ResourceManager.GetString("ErrorServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ..
        /// </summary>
        public static string ErrorValidate {
            get {
                return ResourceManager.GetString("ErrorValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dung lượng file tải lên vượt quá {0}..
        /// </summary>
        public static string FileCapacityExceeded {
            get {
                return ResourceManager.GetString("FileCapacityExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File không có dữ liệu..
        /// </summary>
        public static string FileEmpty {
            get {
                return ResourceManager.GetString("FileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\NguyenVanDuong\MISA\KHOI_TCDN\NguyenVanDuong_MF1534_Web12\MISA-AMIS-BACKEND/Kết quả kiểm tra.xlsx.
        /// </summary>
        public static string FileExportEmployeeValidate {
            get {
                return ResourceManager.GetString("FileExportEmployeeValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File không đúng định dạng..
        /// </summary>
        public static string FileNcorrectFormat {
            get {
                return ResourceManager.GetString("FileNcorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\NguyenVanDuong\MISA\KHOI_TCDN\NguyenVanDuong_MF1534_Web12\MISA-AMIS-BACKEND\Danh_sach_nhan_vien.xlsx.
        /// </summary>
        public static string FileTemplateExportEmployee {
            get {
                return ResourceManager.GetString("FileTemplateExportEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\NguyenVanDuong\MISA\KHOI_TCDN\NguyenVanDuong_MF1534_Web12\MISA-AMIS-BACKEND\Mau_danh_muc_nhan_vien.xlsx.
        /// </summary>
        public static string FileTemplateImportEmployee {
            get {
                return ResourceManager.GetString("FileTemplateImportEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp.
        /// </summary>
        public static string IdentityDateName {
            get {
                return ResourceManager.GetString("IdentityDateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chứng minh nhân dân đã tồn tại..
        /// </summary>
        public static string IdentityNumberAlreadyExist {
            get {
                return ResourceManager.GetString("IdentityNumberAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không hợp lệ..
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không được vượt quá {0} ký tự..
        /// </summary>
        public static string InValidMaxLength {
            get {
                return ResourceManager.GetString("InValidMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhân viên.
        /// </summary>
        public static string NameSheetExportEmployee {
            get {
                return ResourceManager.GetString("NameSheetExportEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu cơ bản.
        /// </summary>
        public static string NameSheetExportEmployeeValidate {
            get {
                return ResourceManager.GetString("NameSheetExportEmployeeValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không đúng định dạng..
        /// </summary>
        public static string NcorrectFormat {
            get {
                return ResourceManager.GetString("NcorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có sự thay đổi..
        /// </summary>
        public static string NotContent {
            get {
                return ResourceManager.GetString("NotContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không được để trống..
        /// </summary>
        public static string NotEmtity {
            get {
                return ResourceManager.GetString("NotEmtity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILE MẪU DANH SÁCH NHÂN VIÊN ĐỂ NHẬP VÀO PHẦN MỀM AMIS ACCOUNTING.
        /// </summary>
        public static string TitleFileTemplateImport {
            get {
                return ResourceManager.GetString("TitleFileTemplateImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp lệ..
        /// </summary>
        public static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
    }
}
