name: Deploy DATN
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t kienvipmkvn/front-nginx . --build-arg VUE_APP_BASE_API_URL=/api/v1
      - run: docker build -t kienvipmkvn/be ./DATN-GracefulStyleShop-BE

      - run: docker push kienvipmkvn/front-nginx
      - run: docker push kienvipmkvn/be

      - name: Generate deployment package
        run: zip -r datn.zip . -x '*.git*'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: DATN2023
          environment_name: DATN2023-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-1-028273443908
          region: ap-southeast-1
          version_label: ${{ github.sha }}
          deployment_package: datn.zip