name: Deploy DATN
on:
  pull_request:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t kienvipmkvn/front-admin ./DATN-GracefulStyleShop-ADMIN --build-arg VUE_APP_BASE_API_URL=http://dtkien.ap-southeast-1.elasticbeanstalk.com/api/v1
      - run: docker build -t kienvipmkvn/be ./DATN-GracefulStyleShop-BE --build-arg MYSQL_SERVER=${{ secrets.MYSQL_SERVER }} --build-arg MYSQL_PORT=${{ secrets.MYSQL_PORT }} --build-arg MYSQL_INITIAL_CATALOG=${{ secrets.MYSQL_INITIAL_CATALOG }} --build-arg MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }} --build-arg MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
      - run: docker build -t kienvipmkvn/multi-nginx ./nginx

      - run: docker push kienvipmkvn/front-admin
      - run: docker push kienvipmkvn/multi-nginx
      - run: docker push kienvipmkvn/be

      - name: Generate deployment package
        run: zip -r datn.zip . -x '*.git*'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: DTKIEN-DATN
          environment_name: DTKIEN-DATN-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-1-028273443908
          region: ap-southeast-1
          version_label: ${{ github.sha }}
          deployment_package: datn.zip